### ISSUE TITLE
Geshi Tags / Fenced Blocks

### ISSUE THREAD

**Issue by jcrawford** [ludovicchabant/PieCrust#128]
Is there any way to use fenced blocks rather than Geshi with PieCrust?

I would love to be able to do 

<pre>
```php
content here 
```
</pre>

rather than 

<pre>
{% geshi 'php' %}

{% endgeshi %}
</pre>

The reason being is most Markdown preview/editors understand the fenced blocks and not the geshi tags.

**Comment by ludovicchabant** [comment]
Totally overdue closing of this request :)

Note that fenced code blocks work in PieCrust 2, along with a bunch of stuff like [Github's language specifiers](https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html). PHPMarkdown options may not work exactly (since it's a different implementation) but equivalent options surely exist.
